SPK_NAME = smartmontools
SPK_VERS = 7.4
SPK_REV = 1
SPK_ICON = src/smartmontools.png

DEPENDS = cross/$(SPK_NAME)

UNSUPPORTED_ARCHS = $(PPC_ARCHS)

MAINTAINER = cosandr
DESCRIPTION = Control and monitor S.M.A.R.T. enabled ATA and SCSI Hard Drives
STARTABLE = no
DISPLAY_NAME = smartmontools
CHANGELOG = "1. Initial release."

HOMEPAGE = https://www.smartmontools.org
LICENSE  = GPLv2+

include ../../mk/spksrc.spk.mk
